eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon

turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-client-feign,eureka-client-ribbon
  cluster-name-expression: ew String("default")
