eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /service/a/**
      serviceId: service-ribbon1
    api-b:
      path: /service/b/**
      serviceId: service-ribbon2