server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yilei111/SpringcloudConfig/ #配置git仓库地址
          searchPaths: respo #配置仓库路径
          username: #访问git仓库的用户名
          password: #访问git仓库的用户密码
      label: master #配置仓库的分支

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

